Documentation: Complete draft of Stable Release Updates (SRU) docs
canonical/ubuntu-packaging-guide pull request #69
Opened 2024-08-17 01:42 UTC by activus-d

This PR adds explanation docs for Stable Release Update (SRU), thereby solving [issue 102](https://github.com/canonical/open-documentation-academy/issues/102) of the open-documentation-academy repository.

2024-08-21 07:50 UTC, dviererbe commented
Hey @activus-d thanks for this awesome contribution! I just want to let you know that I have seen this and will get to review it in the next days. @rkratky could you also take a look?

2024-08-21 07:55 UTC, dviererbe commented on docs/reference/glossary.rst
> +        See also: `Ubuntu SRU Team <https://wiki.ubuntu.com/StableReleaseUpdates#Contacting_the_SRU_team>_
**issue**: ReadTheDocs fails to build this PR with this warning:
```
/home/docs/checkouts/readthedocs.org/user_builds/canonical-ubuntu-packaging-guide/checkouts/69/docs/reference/glossary.rst:1299: WARNING: Inline interpreted text or phrase reference start-string without end-string. [docutils]
```

I think the problem is this:
```suggestion
        See also: `Ubuntu SRU Team <https://wiki.ubuntu.com/StableReleaseUpdates#Contacting_the_SRU_team>`_
```

2024-08-21 08:00 UTC, dviererbe commented
**note**: the linkcheck failure can be ignored, because it is already solved in #53 that has to be merged yet.

2024-08-21 08:02 UTC, dviererbe commented on docs/reference/glossary.rst
> +        See also: `Ubuntu SRU Team <https://wiki.ubuntu.com/StableReleaseUpdates#Contacting_the_SRU_team>_
RTD build succeeded now with that patch 🎉

2024-08-21 13:23 UTC, rkratky commented
> Hey @activus-d thanks for this awesome contribution! I just want to let you know that I have seen this and will get to review it in the next days.

Same here!

2024-09-12 14:56 UTC, dviererbe requested changes
The text seems fine, thank you very much for it!

Please make sure that one type of a link only occurs once, otherwise the page is visually very dense. We started to do the same on other pages (I know the pain of fixing this, because I had to do the same, sorry :/).

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +After publication of the :term:`Ubuntu Stable Release`, there may be a need
nitpick: There is always more than one stable release

```suggestion
After publication of a :term:`Ubuntu Stable Release`, there may be a need
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +updates through a special process known as :term:`Stable Release Update (SRU) <Stable Release Update>`.
nitpick: This page explains this process. There is no value in linking to the glossary.

```suggestion
updates through a special process known as Stable Release Update (SRU).
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:term:`SRU` require great caution because they're automatically recommended to a large
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
SRU's require great caution because they're automatically recommended to a large
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +You can propose an :term:`SRU` in the following cases:
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
You can propose an SRU in the following cases:
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +  vulnerabilities, severe :ref:`regressions <Regressions>` from the previous release, or
nitpick: There is already a link to the glossary entry above.

```suggestion
  vulnerabilities, severe regressions from the previous release, or
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +- To update commercial software in the :term:`Canonical` partner archive.
thought: Maybe the term `Canonical partner archive` should be defined in the glossary.

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +You can stage and bundle low-priority uploads with a future :term:`SRU` or
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
You can stage and bundle low-priority uploads with a future SRU or
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:term:`SRU` bug, then contact the :term:`Ubuntu ESM Team`.
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
SRU bug, then contact the :term:`Ubuntu ESM Team`.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +The general requirements for :term:`SRU` are designed to ensure the stability and
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
The general requirements for SRU are designed to ensure the stability and 
```

2024-09-12 14:56 UTC, dviererbe commented on docs/reuse/links.txt
> +.. _contact the Ubuntu SRU Team: https://wiki.ubuntu.com/StableReleaseUpdates#Contacting_the_SRU_team
nitpick: Please put these at the bottom of `docs/explanation/releases.rst`. They are not reused on multiple pages.

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +To prevent future :ref:`regressions <Regressions>` when users upgrade to newer
nitpick: There is already a link to the glossary entry above.

```suggestion
To prevent future regressions when users upgrade to newer
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +considered for an :term:`SRU`.
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
considered for an SRU.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +Ubuntu versions, bugs should be fixed in the current development release before being
nitpick: link to the glossary entry of the `Current Release in Development`

```suggestion
Ubuntu versions, bugs should be fixed in the :term:`current development release <Current Release in Development>` before being
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +   will be invalidated by the :term:`Ubuntu SRU Team`, and the corresponding uploads
nitpick: There is already a link to the glossary entry above.

```suggestion
   will be invalidated by the Ubuntu SRU Team, and the corresponding uploads
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +7. Once the :term:`Ubuntu SRU Team` reviews and accepts your upload, test the binaries
nitpick: There is already a link to the glossary entry above.

```suggestion
7. Once the Ubuntu SRU Team reviews and accepts your upload, test the binaries
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +   results. The :term:`Ubuntu SRU Team` will evaluate the testing feedback and move the
nitpick: There is already a link to the glossary entry above.

```suggestion
   results. The Ubuntu SRU Team will evaluate the testing feedback and move the
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +5. Prepare the :term:`SRU` upload, attach a ``debdiff`` to the bug, and request sponsorship
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
5. Prepare the SRU upload, attach a ``debdiff`` to the bug, and request sponsorship
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +   :ref:`Ubuntu releases <UbuntuReleases>`. Also, include a reference to the :term:`SRU` bug
nitpick: There is already a link to the glossary entries above.
```suggestion
   Ubuntu releases. Also, include a reference to the SRU bug
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:term:`SRU` in Ubuntu:
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
SRU in Ubuntu:
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +   between :ref:`releases <UbuntuReleases>`, add the new source package as ``Also affecting``
nitpick: There is already a link to the releases above.

```suggestion
   between releases, add the new source package as ``Also affecting``
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +    :ref:`regressions <Regressions>` might happen. This section should show that
nitpick: There is already a link above.
```suggestion
    regressions might happen. This section should show that
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +    to ensure there are no :ref:`regressions <Regressions>`.
nitpick: There is already a link above.
```suggestion
    to ensure there are no regressions.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +If an :term:`SRU` upload triggers an :term:`autopkgtests <autopkgtest>` regression,
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
If an SRU upload triggers an :term:`autopkgtests <autopkgtest>` regression,
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +the issue is resolved. Once the tests are completed, the pending :term:`SRU` page provides
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
the issue is resolved. Once the tests are completed, the pending SRU page provides
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:term:`SRU`, :term:`Canonical` will test each proposed kernel.
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
SRU, :term:`Canonical` will test each proposed kernel.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +Also, updates will be removed from :ref:`proposed <ArchivePockets_Proposed>` if
nitpick: There is already a link above.

```suggestion
Also, updates will be removed from proposed if
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +will remove the package from :ref:`proposed <ArchivePockets_Proposed>` and close the bug
nitpick: There is already a link above.

```suggestion
will remove the package from proposed and close the bug
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:ref:`regressions <Regressions>`.
nitpick: There is already a link above.
```suggestion
test verifies that the update didn't introduce hardware-independent regressions.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +#. Set the ``verification-failed-$RELEASE`` tag on the corresponding :term:`SRU` bug report.
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
#. Set the ``verification-failed-$RELEASE`` tag on the corresponding SRU bug report.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +   to the new bug. If there is more than one bug in the :term:`SRU` changelog, follow up to
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
   to the new bug. If there is more than one bug in the SRU changelog, follow up to
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +#. Follow up on the :term:`SRU` bug report referenced from the package changelog, pointing
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
#. Follow up on the SRU bug report referenced from the package changelog, pointing
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:term:`SRU` verification should be done in a software environment that closely resembles
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
SRU verification should be done in a software environment that closely resembles
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +investigate the cause and address the crash in a follow-up :term:`SRU`. If not,
nitpick: This page already established the acronym. There is no value in linking to the glossary.

```suggestion
investigate the cause and address the crash in a follow-up SRU. If not,
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:ref:`proposed <ArchivePockets_Proposed>`, follow up on the bug with a detailed
nitpick: There is already a link above.

```suggestion
proposed, follow up on the bug with a detailed
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +Packages accepted into :ref:`proposed <ArchivePockets_Proposed>` automatically trigger
nitpick: There is already a link above.

```suggestion
Packages accepted into proposed automatically trigger
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:ref:`proposed <ArchivePockets_Proposed>`, do the following:
nitpick: There is already a link above.

```suggestion
proposed, do the following:
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +``verification-failed-$RELEASE``. If the fix is sufficent, the :term:`SRU Verification Team`
nitpick: There is already a link above.

```suggestion
``verification-failed-$RELEASE``. If the fix is sufficent, the SRU Verification Team
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +#. `Ask a bug supervisor`_ to target the bug to the appropriate :ref:`Ubuntu releases <UbuntuReleases>`.
nitpick: There is already a link to the releases above.

```suggestion
#. `Ask a bug supervisor`_ to target the bug to the appropriate Ubuntu releases.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:ref:`Ubuntu release <UbuntuReleases>`.
nitpick: There is already a link to the releases above.

```suggestion
as new bugs or failures in previously well-functioning aspect of an Ubuntu release. 
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +To minimise the risk of :ref:`regressions <Regressions>` being introduced through
nitpick: There is already a link above.

```suggestion
To minimise the risk of regressions being introduced through
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +hours to monitor for :ref:`regressions <Regressions>`. If no issues are detected, the
nitpick: There is already a link above.

```suggestion
hours to monitor for regressions. If no issues are detected, the
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +:ref:`regressions <Regressions>`, both in manual and automated testing.
nitpick: There is already a link above.

```suggestion
regressions, both in manual and automated testing.
```

2024-09-12 14:56 UTC, dviererbe commented on docs/explanation/stable-release-updates.rst
> +the target package will not be released into :ref:`updates <ArchivePockets_Updates>` until
nitpick: There is already a link above.
```suggestion
the target package will not be released into updates until
```

2024-09-13 05:42 UTC, activus-d commented
> The text seems fine, thank you very much for it!
> 
> Please make sure that one type of a link only occurs once, otherwise the page is visually very dense. We started to do the same on other pages (I know the pain of fixing this, because I had to do the same, sorry :/).

@dviererbe Thanks for the feedback. I have implemented them and the docs is now available for your review.

2024-10-03 14:42 UTC, merged