docs(reference/rust-toolchain-packaging): add maintenance guide for Rust
canonical/ubuntu-packaging-guide pull request #78
Opened 2024-11-28 17:36 UTC by liushuyu

This pull request adds the Rust toolchain maintenance guide.

2025-02-21 12:32 UTC, dviererbe requested changes
@rkratky: I think this is not appropriate for the packaging guide. Does my logic (see below) make sense to you? I would really like to hear your perspective on this.

2025-02-21 12:32 UTC, dviererbe commented on docs/reference/rust-toolchain-packaging.rst
> +be explained below for your reference.
**suggestion(blocking):** The first part of this document should maybe be part of the [Ubuntu Developer Docs](https://github.com/canonical/ubuntu-for-developers-docs). This feels too specific for the generic packaging guide.

2025-02-21 12:32 UTC, dviererbe commented on docs/reference/rust-toolchain-packaging.rst
> +Finally you can test build the package locally or in a PPA.
**note:** this looks to me more like a how-to rather than a reference

**suggestion(blocking):** This part should be a `debian/README.source` or `debian/README.Ubuntu` file of the rust package. (See [Debian Policy 4.14. Source package handling: `debian/README.source`](https://www.debian.org/doc/debian-policy/ch-source.html#source-package-handling-debian-readme-source)). It feels too specific/niche topic to me for the generic Ubuntu packaging guide. We would need to include all special cases of source package handling in this guide if we start including this.

2025-02-21 12:33 UTC, dviererbe commented
**note:** I am closing this PR for now. We can always re-open this later. Please feel free to continue the discussion!

2025-02-21 12:33 UTC, closed without merging

2025-02-24 08:42 UTC, rkratky commented
> @rkratky: I think this is not appropriate for the packaging guide. Does my logic (see below) make sense to you? I would really like to hear your perspective on this.

I agree, but it's really useful info, too. I'm wondering if we could have a separate section in the PG for such specific guidance.